# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    hooks:
    -   id: check-docstring-first
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-yaml
    -   id: check-added-large-files
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    hooks:
    -   id: remove-tabs
  - repo: https://github.com/psf/black
    hooks:
    -   id: black
  - repo: https://github.com/asottile/blacken-docs
    hooks:
    -   id: blacken-docs
  - repo: https://github.com/PyCQA/flake8
    hooks:
    -   id: flake8
  - repo: https://github.com/roy-ht/pre-commit-jupyter
    hooks:
      - id: jupyter-notebook-cleanup
        args:
          - --pin-patterns
          - "[pin];[donotremove]"
  - repo: https://github.com/econchick/interrogate
    hooks:
      - id: interrogate
        exclude: ^(tests/|docs/)
        args:
          - -vv
          - -i
          - --fail-under=95
          - --omit-covered-files

default_language_version:
    python: python3.9
