name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
  Test_with_tox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run tox
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
        run: |
          pip install --disable-pip-version-check tox
          tox
